### ISSUE TITLE
Make unsubscribe form

### ISSUE THREAD

**Issue by geowa4** [585-software/rocdev#4]
The path `/unsubscribe` exists, but it's essentially a static page. Make it a form for with a single field for the email address. The code for calling the Sparkpost API can be found in https://github.com/geowa4/elixir-sparkpost-experiements.

**Comment by dantswain** [comment]
I AM ALL TAKING YOUR ASSIGNMENTS

**Comment by geowa4** [comment]
I was able to set up unsubscribe links using https://www.sparkpost.com/docs/user-guide/setting-up-unsubscribe-links/.

**Comment by geowa4** [comment]
Why doesn't GitHub refresh pages automatically...
